# Generated by Django 5.0.6 on 2026-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('issuer', models.CharField(max_length=200)),
                ('date', models.CharField(help_text='E.g. "Mar 2025"', max_length=50)),
                ('url', models.URLField(blank=True, help_text='Verification link')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='E.g. "Jan 2025 – Apr 2025"', max_length=100)),
                ('exp_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Full-time Job'), ('education', 'Education'), ('freelance', 'Freelance')], default='internship', max_length=20)),
                ('description', models.JSONField(default=list, help_text='Array of bullet point strings')),
                ('tools', models.JSONField(default=list, help_text='["Python", "Django", ...]')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Short 1-line description shown in compact view')),
                ('short_desc', models.CharField(blank=True, help_text='One-line descriptor for card subtitle', max_length=300)),
                ('full_desc', models.TextField(blank=True, help_text='Expanded description shown in featured/wide card')),
                ('category', models.CharField(choices=[('Web Dev', 'Web Dev'), ('ML & AI', 'ML & AI'), ('Data', 'Data'), ('Tools', 'Tools')], default='Web Dev', max_length=50)),
                ('tech', models.JSONField(default=list, help_text='e.g. ["Django", "React", "Docker"]')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('highlight', models.CharField(blank=True, help_text='E.g. "Published IJISRT Paper — DOI: ..."', max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_visibility', models.JSONField(default=dict, help_text='Map of section names to booleans, e.g. {"hero": true, "about": true, "skills": true, "projects": true, "experience": true, "publications": true, "certifications": true, "contact": true}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='💻', help_text='Emoji or short icon string', max_length=10)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('AI/ML', 'AI/ML'), ('DevOps & Cloud', 'DevOps & Cloud'), ('Data & ML', 'Data & ML'), ('Tools', 'Tools')], max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
