# Generated by Django 5.0.6 on 2026-04-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('tagline', models.CharField(default='', max_length=300)),
                ('roles', models.JSONField(default=list, help_text='["Role 1", "Role 2"]')),
                ('availability', models.CharField(default='', max_length=200)),
                ('photo', models.CharField(blank=True, default='', max_length=300)),
                ('bio', models.JSONField(default=list, help_text='Array of paragraph strings')),
                ('stats', models.JSONField(default=dict, help_text='{"projects": "4+", "internships": "2", "cgpa": "7.5"}')),
                ('info', models.JSONField(default=dict, help_text='{"location": "...", "degree": "...", ...}')),
                ('social', models.JSONField(default=dict, help_text='{"github": "...", "linkedin": "...", ...}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
