# Generated by Django 5.0.6 on 2026-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture_diagram',
            field=models.TextField(blank=True, help_text='ASCII diagram or SVG code'),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.JSONField(blank=True, default=list, help_text='[{problem, solution}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='[{icon, title, description}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='metrics',
            field=models.JSONField(blank=True, default=list, help_text='[{value, label}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='What problem does it solve?'),
        ),
        migrations.AddField(
            model_name='project',
            name='roadmap',
            field=models.JSONField(blank=True, default=list, help_text='[{step, description}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, help_text='[{url, caption}]'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, help_text='One line pitch', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_decisions',
            field=models.JSONField(blank=True, default=list, help_text='[{question, answer}]'),
        ),
    ]
